######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 2 21:48:17 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DummyDTW.h DummySignal.h PlotDTW.h
FORMS += PlotDTW.ui
SOURCES += DummyDTW.cpp \
           DummySignal.cpp \
           PlotDTW.cpp \
           PlotDTWTester.cpp \
