######################################################################
# Automatically generated by qmake (2.01a) Thu Dec 10 00:50:32 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DummyDTW.h DummySignal.h PlotDTW.h
FORMS += PlotDTW.ui
SOURCES += DummyDTW.cpp \
           DummySignal.cpp \
           PlotDTW.cpp \
           PlotDTWTester.cpp \
           stubTester.cpp
