######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 11 14:48:15 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DTW.h DummyDTW.h DummySignal.h PlotDTW.h Signal.h
FORMS += PlotDTW.ui
SOURCES += DTW.cpp DummyDTW.cpp DummySignal.cpp PlotDTW.cpp proj3.cpp Signal.cpp
