######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 12 17:49:54 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DTW.h PlotDTW.h Signal.h
FORMS += PlotDTW.ui
SOURCES += DTW.cpp PlotDTW.cpp proj3.cpp Signal.cpp
