#############################################################################
# Makefile for building: DTW
# Generated by qmake (2.01a) (Qt 4.6.2) on: Wed Dec 2 23:20:13 2015
# Project:  DTW.pro
# Template: app
# Command: /usr/lib64/qt4/bin/qmake -unix -o Makefile DTW.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)   -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib64/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = DummyDTW.cpp \
		DummySignal.cpp \
		PlotDTW.cpp \
		PlotDTWTester.cpp moc_PlotDTW.cpp
OBJECTS       = DummyDTW.o \
		DummySignal.o \
		PlotDTW.o \
		PlotDTWTester.o \
		moc_PlotDTW.o
DIST          = /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		DTW.pro
QMAKE_TARGET  = DTW
DESTDIR       = 
TARGET        = DTW

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_PlotDTW.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DTW.pro  /usr/lib64/qt4/mkspecs/linux-g++-64/qmake.conf /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile DTW.pro
/usr/lib64/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile DTW.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/DTW1.0.0 || $(MKDIR) .tmp/DTW1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DTW1.0.0/ && $(COPY_FILE) --parents DummyDTW.h DummySignal.h PlotDTW.h .tmp/DTW1.0.0/ && $(COPY_FILE) --parents DummyDTW.cpp DummySignal.cpp PlotDTW.cpp PlotDTWTester.cpp .tmp/DTW1.0.0/ && $(COPY_FILE) --parents PlotDTW.ui .tmp/DTW1.0.0/ && (cd `dirname .tmp/DTW1.0.0` && $(TAR) DTW1.0.0.tar DTW1.0.0 && $(COMPRESS) DTW1.0.0.tar) && $(MOVE) `dirname .tmp/DTW1.0.0`/DTW1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DTW1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_PlotDTW.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_PlotDTW.cpp
moc_PlotDTW.cpp: DummyDTW.h \
		DummySignal.h \
		PlotDTW.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) PlotDTW.h -o moc_PlotDTW.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_PlotDTW.h
compiler_uic_clean:
	-$(DEL_FILE) ui_PlotDTW.h
ui_PlotDTW.h: PlotDTW.ui
	/usr/lib64/qt4/bin/uic PlotDTW.ui -o ui_PlotDTW.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

DummyDTW.o: DummyDTW.cpp DummyDTW.h \
		DummySignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DummyDTW.o DummyDTW.cpp

DummySignal.o: DummySignal.cpp DummySignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DummySignal.o DummySignal.cpp

PlotDTW.o: PlotDTW.cpp PlotDTW.h \
		DummyDTW.h \
		DummySignal.h \
		ui_PlotDTW.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PlotDTW.o PlotDTW.cpp

PlotDTWTester.o: PlotDTWTester.cpp DummySignal.h \
		DummyDTW.h \
		PlotDTW.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PlotDTWTester.o PlotDTWTester.cpp

moc_PlotDTW.o: moc_PlotDTW.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PlotDTW.o moc_PlotDTW.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

